### ISSUE TITLE
fr: style issue on consecutive headings

### ISSUE THREAD

**Issue by Airthee** [nuxt/nuxtjs.org#267]
### Version

[master](https://github.com/docs/releases/tag/master)

### Reproduction link

[https://fr.nuxtjs.org/guide/directory-structure#r-pertoires](https://fr.nuxtjs.org/guide/directory-structure#r-pertoires)

### Steps to reproduce

1. Just go to the url and see the title

### What is expected ?

New line after h2

### What is actually happening?

h3 is on the same line as h2 :
![image](https://user-images.githubusercontent.com/13355624/66592066-9b9dad80-eb94-11e9-981c-1541d0100dfd.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c226">#c226</a>)</em></sub></div>

**Comment by KarineLiuti** [comment]
I think this problem was solved. When I clicked the link, the titles was ok.

**Comment by Airthee** [comment]
@KarineLiuti 
The problem is still on this page : https://nuxtjs.org/guide/release-notes#v2.5.0
